# Generated by Django 4.2.13 on 2024-08-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="authors",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.category",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="authors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.author",
            ),
        ),
    ]
