# Generated by Django 4.2.13 on 2024-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default='Sustainable Development', max_length=255),
        ),
    ]
