# Generated by Django 4.2.13 on 2024-08-22 17:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='heading',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(),
        ),
    ]
